### ISSUE TITLE
Object.promiseMethodWrapper [as getVideoMetaData]

### ISSUE THREAD

**Issue by vvusts** [numandev1/react-native-compressor#129]
### Current behavior
getVideoMetaData doesn;t work on android.

```
at Object.promiseMethodWrapper [as getVideoMetaData] (NativeModules.js:104:51)
    at getVideoMetaData (index.tsx:49:21)
    at RecordVideoTask.videoSelected$ (index.js:231:52)
    at tryCatch (regeneratorRuntime.js:72:17)
    at Generator._invoke (regeneratorRuntime.js:55:24)
    at Generator.next (regeneratorRuntime.js:97:21)
    at tryCatch (regeneratorRuntime.js:72:17)
    at invoke (regeneratorRuntime.js:103:20)
    at regeneratorRuntime.js:108:11
    at tryCallOne (core.js:37:12)
```

### Expected behavior
To get metadata on android same as on IOS.
### Platform

- [X] Android
- [] iOS

### React Native Version
0.64.3
### React Native Compressor Version
1.6.1
### Reproducible Steps And Demo
```
const fp = await Video.compress(path);
const metaData = await getVideoMetaData(fp);
```

**Comment by numandev1** [comment]
🙏 sorry for a long ago I was not maintaining due to the huge office workload, hopefully, I am going to start fixing bugs on a weekend basis,
I will fix at least 2 issues on the weekend, for priority bugs you can join the discord channel https://discord.gg/dtYzk8sp where we can discuss which bug is most important

**Comment by numandev1** [comment]
fixed in the latest version, please feel free to reopen this issue again if this issue happens again
